sylius_resource:
    resources:
        app.post:
            classes:
                model: AppBundle\Entity\Post
            translation:
                classes:
                    model: AppBundle\Entity\PostTranslation
