shop_posts:
    pattern: /shop/latest-news
    defaults:
        _controller: 'app.controller.posts:indexAction'
    methods: [ GET ]

post:
    resource: |
        alias: app.post
        grid: app_post
        templates: SyliusAdminBundle:Crud
        redirect: update
        except: [ 'show ']
    type: sylius.resource
    prefix: /admin
