services:
    app_admin_menu_listener:
        class: AppBundle\Menu\MenuListener
        tags:
            -
                name: kernel.event_listener
                event: sylius.menu.admin.main
                method: buildMenu
