services:
    app.menu.admin_menu_listener:
        class: AppBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: onMenuConfigure }

    app.controller.posts:
        class: AppBundle\Controller\PostsController
        arguments:
            - @templating
            - @doctrine.orm.entity_manager
