services:
    app.menu.admin_menu_listener:
        class: AppBundle\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: onMenuConfigure }
