sylius_grid:
    grids:
        app_post:
            driver:
                options:
                    class: AppBundle\Entity\Post
            fields:
                title:
                    type: string
                publishedAt:
                    type: datetime
                    options:
                        format: Y-m-d H:i:s

            actions:
                main:
                    create:
                        type: create

                item:
                    update:
                        type: update
                    delete:
                        type: delete
