sylius_resource:
    resources:
        app.post:
            classes:
                model: AppBundle\Entity\Post
            translation:
                classes:
                    model: AppBundle\Entity\PostTranslation

sylius_customer:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Customer
                form:
                    default: AppBundle\Form\CustomerType
